### ISSUE TITLE
fix dependency for HOSTNAME 

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/analytics_engine#28]

**Comment by cjdcordeiro** [comment]
@sandlbn will tell where does landscaper take the hostname from, within device-dynamic (or device...whatever)

@sandlbn where do you take the hostname from in the host? (is it cat /proc/sys/kernel/hostname ? )

@ssgUPC make sure that that attribute, has the hostname populated from the same source as landscaper (how? just bind mount cat /proc/sys/kernel/hostname  into your container and take its value as the real hostname)

**Comment by ssgUPC** [comment]
actually, if you see the docker-compose file I guess there is some field called hostname? do I need to add this hostname into device or device-dynamic schema?

**Comment by cjdcordeiro** [comment]
@ssgUPC wait for @sandlbn 's reply. Your hostname needs to match exactly the one he's getting from landscaper/snap

**Comment by rosogon** [comment]
Hi @sandlbn. Any comment on this?

**Comment by sandlbn** [comment]
@rosogon and @ssgUPC We are taking it from python os/sys module, the container has mounted procfs filesystem. Then if it matches /proc/sys/kernel/hostname should be fine.

**Comment by ssgUPC** [comment]
@sandlbn, I remember when I was starting to develop the res-cat module initially, I added the hostname but then after a bit discussion, I removed that part...actually, I was collecting the hostname using the os/system python module. But, one question, where should I add the hostname in device or device-dynamic?

**Comment by sandlbn** [comment]
@ssgUPC, to be honest, I don't know which part of your code relies on hostname but it could be that hwlock filename needs to contain hostname.  Then if hwlock data is stored in db I do believe that should be already there. Would prefer to have it working as it is but without dependency on hostname key in docker compose file.

**Comment by rosogon** [comment]
@sandlbn , setting the right hostname in resource-categorizer, I finally have data in service-container-metric resource.

**Comment by cjdcordeiro** [comment]
@ssgUPC in https://github.com/mF2C/ResourceManagement/blob/master/Resource-Categorization/X86%20based/device_static.py#L141 you need to replace `<info name="HostName" value=..../>` with `<info name="HostName" value=XX/>` where `XX=open("/proc/sys/kernel/hostname").read()`

**Comment by ssgUPC** [comment]
@cjdcordeiro thanks for this info..I have successfully collected the hostname from the host machine...but my problem is that I haven't any experienced to modify the XML file. So, I'm sorry to say that I need some sample example how to modify it.

**Comment by sandlbn** [comment]
@ssgUPC  https://stackoverflow.com/questions/17922056/setting-an-attribute-value-in-xml-file-using-elementtree

**Comment by ssgUPC** [comment]
okay perfect I'll modify that. thanks.

**Comment by ALEJANDROJ19** [comment]
@sandlbn please verify if latest version of res-cat (published in Master) is actually doing this correctly.

**Comment by ssgUPC** [comment]
@cjdcordeiro as I said you earlier, please don't remove the `hostname` variable from d-c file...actually...if you remove this one then I need to modify my code again...because in my code, what I'm doing now, I'm looking for the `IRILD039` - this string in `hwloc` info and change it with the actual `hostname` of the machine.

**Comment by sandlbn** [comment]
@ALEJANDROJ19 @ssgUPC 
I tested code and it mostly working. Yay. But, there is something wrong with hostname in device collection. 

here is what suppose to be in devices hwlock ```<info name="HostName" value="as2"/>```
here is what I got ```<info name=\"HostName\" value=\"as2\n\"/>  ```

**Comment by ssgUPC** [comment]
Okay, I see.... I know that one....okay...let me fix this one and will let you know soon.

**Comment by ssgUPC** [comment]
@sandlbn now, could you please check with the [mf2c/trunk:resCatlatest-V2.0.30](https://cloud.docker.com/u/mf2c/repository/registry-1.docker.io/mf2c/trunk/tags)....though I have to modify the docker-health issues so....I'll not going to add this version to the d-c file...atleast for now....so locally, you can use this version...later when I modify the version in d-c file....I'll let you know.
